[package]
name = "hourglass_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.2.1"
derive_more = "0.99.17"
lazy_static = "1.4.0"
log = "0.4.19"
